version: '3.8'

services:
  db:
    image: postgres:16
    container_name: photo_gallery_db
    environment:
      POSTGRES_DB: gallery
      POSTGRES_USER: gallery
      POSTGRES_PASSWORD: gallery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
